### PR TITLE
updated

### PR DESCRIPTION
**Pull request by MccGrey**
please merge to main

### CODE REVIEW

**Comment by tolujacob05** [comment]
okay

**Comment by tolujacob05** [comment]
Im trying to merge to main but i dont know why i am getting this 
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/tolujacob05/HOTEL-project.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/tolujacob05/HOTEL-project.git'

**Comment by tolujacob05** [comment]
but if i pull from main i get the updated file on my vs code.

**Review by odeyemitobi — APPROVED** [review]
Good to go🤣😁

**Pull request merged**
